// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCtDtTxqke0glnsPjAyrjGCVEhKZ8td4',
    appId: '1:21033953061:web:a85bae34dbcb909ef21ccc',
    messagingSenderId: '21033953061',
    projectId: 'flavor-b4545',
    authDomain: 'flavor-b4545.firebaseapp.com',
    storageBucket: 'flavor-b4545.firebasestorage.app',
    measurementId: 'G-JL2H9KREJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-dSoj7hSt9OdwqQun6OPyYTfTqkSGos',
    appId: '1:21033953061:android:737e1440c62ae9d0f21ccc',
    messagingSenderId: '21033953061',
    projectId: 'flavor-b4545',
    storageBucket: 'flavor-b4545.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvzF3eWOzHfLdpWkIoQqZXny89sjZ9tls',
    appId: '1:21033953061:ios:a87c20e1f18a944af21ccc',
    messagingSenderId: '21033953061',
    projectId: 'flavor-b4545',
    storageBucket: 'flavor-b4545.firebasestorage.app',
    iosClientId: '21033953061-o3v3qqj1heh2sjq92icccuiu87vv7ii3.apps.googleusercontent.com',
    iosBundleId: 'com.example.rydex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvzF3eWOzHfLdpWkIoQqZXny89sjZ9tls',
    appId: '1:21033953061:ios:a87c20e1f18a944af21ccc',
    messagingSenderId: '21033953061',
    projectId: 'flavor-b4545',
    storageBucket: 'flavor-b4545.firebasestorage.app',
    iosClientId: '21033953061-o3v3qqj1heh2sjq92icccuiu87vv7ii3.apps.googleusercontent.com',
    iosBundleId: 'com.example.rydex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-p4Bmyvu_nlEHeY8j9WrzE7_8Ftz23Jo',
    appId: '1:21033953061:web:d6f8c5e4b45d192ff21ccc',
    messagingSenderId: '21033953061',
    projectId: 'flavor-b4545',
    authDomain: 'flavor-b4545.firebaseapp.com',
    storageBucket: 'flavor-b4545.firebasestorage.app',
    measurementId: 'G-L86TX8CYQW',
  );
}
